version: '2'
services:
    nginx1.15.7:
      build: ./nginx
      container_name: nginx1.15.7
      ports:
        - "80:80"
        - "443:443"
      links:
        - "php7.3"
      volumes:
        - $PWD/html/www/:/usr/share/nginx/html/
        - $PWD/nginx/logs/:/var/log/nginx/
        - $PWD/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
        - $PWD/nginx/conf/public.conf:/etc/nginx/public.conf
        - $PWD/nginx/conf/fastcgi.conf:/etc/nginx/fastcgi.conf
        - $PWD/nginx/conf/conf.d/:/etc/nginx/conf.d/
        - /etc/localtime:/etc/localtime:ro
        - $PWD/letsencrypt/etc:/etc/letsencrypt
        - $PWD/letsencrypt/lib:/var/lib/letsencrypt
        - $PWD/letsencrypt/log:/var/log/letsencrypt
      networks:
        custom_network:
          ipv4_address: 172.18.0.2
    php7.3:
      build: ./php
      container_name: php7.3
      ports:
        - "9000:9000"
        - "9502:9502"
      volumes:
        - $PWD/html/www/:/var/www/html/
        - $PWD/php/conf/:/usr/local/etc/php/
        - /etc/localtime:/etc/localtime:ro
        - $PWD/letsencrypt/etc:/etc/letsencrypt
        - $PWD/letsencrypt/lib:/var/lib/letsencrypt
        - $PWD/letsencrypt/log:/var/log/letsencrypt
      links:
        - "mysql-master"
        - "mysql-slave"
        - "redis5.0.3"
      networks:
        custom_network:
          ipv4_address: 172.18.0.3
    mysql-master:
      build: ./mysql
      container_name: mysql-master
      ports:
        - "3306:3306"
      volumes:
        - $PWD/mysql/conf/:/etc/mysql/conf.d/
        - $PWD/mysql/logs/:/var/log/mysql/
        - $PWD/mysql/data/:/var/lib/mysql/
        - /etc/localtime:/etc/localtime:ro
      environment:
        MYSQL_ROOT_PASSWORD: zxc123
      networks:
        custom_network:
          ipv4_address: 172.18.0.4
    mysql-slave:
      build: ./slave
      container_name: mysql-slave
      ports:
        - "3307:3306"
      volumes:
        - $PWD/slave/conf/:/etc/mysql/conf.d/
        - $PWD/slave/logs/:/var/log/mysql/
        - $PWD/slave/data/:/var/lib/mysql/
        - /etc/localtime:/etc/localtime:ro
      environment:
        MYSQL_ROOT_PASSWORD: zxc123    
      links:
        - "mysql-master"
      networks:
        custom_network:
          ipv4_address: 172.18.0.5
    redis5.0.3:
      build: ./redis
      container_name: redis5.0.3
      ports:
        - "6379:6379"
      volumes:
        - $PWD/redis/data/:/data/
        - $PWD/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
        - /etc/localtime:/etc/localtime:ro
      networks:
        custom_network:
          ipv4_address: 172.18.0.6
    certbot:
      image: certbot/certbot
      container_name: certbot
      volumes:
        - $PWD/letsencrypt/etc:/etc/letsencrypt
        - $PWD/letsencrypt/lib:/var/lib/letsencrypt
        - $PWD/letsencrypt/log:/var/log/letsencrypt
        - $PWD/html/www:/var/www
      networks:
        custom_network:
          ipv4_address: 172.18.0.7
    keepalived2.0.16:
      build: ./keepalived
      container_name: keepalived2.0.16
      volumes:
        - /etc/localtime:/etc/localtime:ro
      networks:
        custom_network:
          ipv4_address: 172.18.0.8
networks:
  custom_network: # 自定义网络名称
    driver: bridge # 桥接
    ipam: # 要使用静态ip必须使用ipam插件
      driver: default
      config:
      - subnet: 172.18.0.0/24
        gateway: 172.18.0.1