# syntax version.
version: "3.7"

services:
  php:
    image: "php-${PHP_VERSION}-alpine"
    container_name: php
    build:
      context: "php/${PHP_VERSION}/alpine/fpm"
    ports:
        - "9000:9000"
    volumes:
        - $PWD/html/www/:/var/www/html/
        - $PWD/html/www/img.shikee.com/:/data/htdocs/img.sylm.com/
        - $PWD/html/www/img.shikee.com/:/home/shi/code/img.shikee.com/
        - $PWD/php/conf/php.ini:/usr/local/etc/php/php.ini
        - $PWD/php/conf/conf.d/99-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    user: 1000:1000
    extra_hosts:
        - "localhost.sql:172.24.0.4"
    networks:
        custom_network:
          ipv4_address: 172.24.0.2
    logging: 
       driver: json-file
       options: 
          max-size: "500m" 
  nginx:
    image: "nginx-${NGINX_VERSION}-alpine"
    container_name: nginx
    build:
      context: "nginx/${NGINX_VERSION}/alpine"
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - $PWD/html/www/:/usr/share/nginx/html/
        - $PWD/nginx/log/:/var/log/nginx/
        - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf
        - $PWD/nginx/public.conf:/etc/nginx/public.conf
        - $PWD/nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
        - $PWD/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
        custom_network:
          ipv4_address: 172.24.0.3
    logging: 
       driver: json-file
       options: 
          max-size: "500m" 
  mysql-master:
    image: "master-mysql-${MYSQL_VERSION}-debian"
    container_name: mysql-master
    build:
      context: "mysql/${MYSQL_VERSION}/debian/master"
    ports:
        - "3306:3306"
    volumes:
        - $PWD/mysql/master/conf.d/:/etc/mysql/conf.d/
        - $PWD/mysql/master/backup/:/var/backup/
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_MASTER_ROOT_PASSWORD}
    networks:
        custom_network:
          ipv4_address: 172.24.0.4
    logging: 
       driver: json-file
       options: 
          max-size: "500m" 
  mysql-slave:
    image: "slave-mysql-${MYSQL_VERSION}-debian"
    container_name: mysql-slave
    build:
      context: "mysql/${MYSQL_VERSION}/debian/slave"
    ports:
        - "3307:3307"
    volumes:
        - $PWD/mysql/slave/conf.d/:/etc/mysql/conf.d/
        - $PWD/mysql/slave/backup/:/var/backup/
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_SLAVE_ROOT_PASSWORD}
    networks:
        custom_network:
          ipv4_address: 172.24.0.5
    logging: 
       driver: json-file
       options: 
          max-size: "500m" 
  redis:
    image: "redis-${REDIS_VERSION}-alpine"
    container_name: redis
    build:
      context: "redis/${REDIS_VERSION}/alpine"
    ports:
        - "6379:6379"
    networks:
        custom_network:
          ipv4_address: 172.24.0.6
    logging: 
       driver: json-file
       options: 
          max-size: "500m"
networks:
  custom_network: # 自定义网络名称
    driver: bridge # 桥接
    ipam: # 要使用静态ip必须使用ipam插件
      driver: default
      config:
        - subnet: "172.24.0.0/16"
